import { NextResponse } from 'next/server'
import { prisma } from '../../../../../../lib/prisma'

export async function GET() {
  try {
    // Get stats from database - persists after logout/login
    const [
      totalTestCases,
      requirementBasedTests,
      avgRiskScore,
      lastGenerated
    ] = await Promise.all([
      // Count total test cases generated by AI
      prisma.qATestCase.count({
        where: {
          generatedBy: 'ai'
        }
      }),
      
      // Count requirement-based tests by checking metadata
      prisma.qATestCase.findMany({
        where: {
          generatedBy: 'ai',
          metadata: {
            not: null
          }
        },
        select: {
          metadata: true
        }
      }).then(testCases => {
        return testCases.filter(tc => {
          try {
            const metadata = typeof tc.metadata === 'string' 
              ? JSON.parse(tc.metadata) 
              : tc.metadata
            return metadata?.requirementBased === true
          } catch {
            return false
          }
        }).length
      }),
      
      // Calculate average risk score from metadata
      prisma.qATestCase.findMany({
        where: {
          generatedBy: 'ai',
          metadata: {
            not: null
          }
        },
        select: {
          metadata: true
        }
      }).then(testCases => {
        const riskScores = testCases
          .map(tc => {
            try {
              const metadata = typeof tc.metadata === 'string' 
                ? JSON.parse(tc.metadata) 
                : tc.metadata
              return metadata?.riskScore || metadata?.risk || 0
            } catch {
              return 0
            }
          })
          .filter(score => score > 0)
        
        return riskScores.length > 0 
          ? riskScores.reduce((sum, score) => sum + score, 0) / riskScores.length
          : 0
      }),
      
      // Get last generated timestamp
      prisma.qATestCase.findFirst({
        where: {
          generatedBy: 'ai'
        },
        orderBy: {
          createdAt: 'desc'
        },
        select: {
          createdAt: true
        }
      })
    ])

    // Calculate requirements estimate (unique components or requirement-based tests)
    const totalRequirements = Math.max(
      requirementBasedTests,
      Math.ceil(totalTestCases / 8) // Estimate: ~8 tests per requirement
    )

    return NextResponse.json({
      success: true,
      stats: {
        totalRequirements,
        totalTestCases,
        avgRiskScore: Number(avgRiskScore.toFixed(1)),
        lastGenerated: lastGenerated?.createdAt || null
      }
    })
    
  } catch (error) {
    console.error('Stats API error:', error)
    return NextResponse.json(
      { error: 'Failed to load stats', details: error.message },
      { status: 500 }
    )
  }
}

